#line 2 ".\\SRC\\tokens.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
// #include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
static yyconst short int yy_accept[124] =
    {   0,
        0,    0,    0,    0,   72,   72,   86,   84,   80,   81,
       79,   45,   68,   47,   48,   42,   50,   84,   52,   53,
       51,   39,   41,   40,   56,   43,   78,   78,   35,   38,
       57,   61,   58,   60,   46,   54,   55,   49,   82,   82,
        2,   82,   36,   44,   37,   59,   65,   64,   85,   72,
       69,   73,   72,   20,    0,   27,   21,   28,    0,   23,
       13,   24,   14,   25,   34,    0,   63,   26,   78,    0,
        0,    0,    0,   62,   12,   16,   18,   19,   17,   15,
       82,    5,   82,    5,   83,    7,    8,    9,   10,   11,
        6,   29,   22,   30,   66,   66,   67,   72,    0,   70,

       71,    0,    3,   33,   75,   76,   74,   77,   62,   31,
       32,    5,    4,    5,   83,    4,    0,    4,    4,    1,
        1,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   26,   26,   26,   27,   28,   29,
       30,   31,   32,   33,   39,   39,   39,   40,   41,   39,
       42,   43,   44,   42,   42,   45,   42,   46,   42,   42,
       42,   47,   48,   49,   42,   42,   42,   50,   42,   42,
       34,   35,   36,   37,   38,    1,   39,   39,   39,   40,

       41,   39,   42,   43,   44,   42,   42,   45,   42,   46,
       42,   42,   42,   47,   48,   49,   42,   42,   42,   50,
       42,   42,   51,   52,   53,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    7,    7,
        7,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[139] =
    {   0,
        0,    0,   52,   53,   54,   55,  231,  232,  232,  232,
      232,  200,  232,  184,  232,  198,   49,    0,  232,  232,
      197,   47,  232,   51,  208,   50,   71,  175,  197,  232,
       40,  193,   41,  232,  232,  232,  232,  232,    0,   78,
      179,   85,  172,   33,  232,  163,  232,  232,   59,    0,
        0,  122,  166,  232,   88,  232,  232,  232,  116,  232,
      232,  232,  232,  232,  232,  104,  232,  232,   65,   74,
       73,   63,   44,    0,  232,   56,  232,  232,  232,   54,
        0,    0,   38,    0,   37,    0,    0,    0,    0,    0,
      232,  232,  232,  232,  232,   69,  232,    0,  127,  232,

      232,   28,  232,  232,  232,  232,  232,  232,    0,  232,
      232,    0,    0,    0,    0,    0,   24,    0,    0,  114,
      121,  128,  232,  154,  161,  168,  171,  174,  176,  183,
      190,  193,  196,  199,  202,  205,  208,  215
    } ;

static yyconst short int yy_def[139] =
    {   0,
      123,    1,  124,  124,  125,  125,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  126,  123,  123,
      123,  123,  123,  123,  123,  123,  123,   27,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  127,  128,
      129,  128,  123,  123,  123,  123,  123,  123,  130,  131,
      131,  123,  131,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,   27,  123,
      123,  123,  123,  132,  123,  123,  123,  123,  123,  123,
      127,  133,  127,  134,  135,  127,  127,  127,  127,  127,
      123,  123,  123,  123,  123,  130,  123,  131,  123,  123,

      123,  123,  123,  123,  123,  123,  123,  123,  132,  123,
      123,  133,  136,  134,  135,  137,  123,  136,  137,  138,
      138,  138,    0,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123
    } ;

static yyconst short int yy_nxt[287] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   28,   28,   28,   28,   28,   29,   30,   31,   32,
       33,   34,   35,   36,    8,   37,   38,   39,   40,   41,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   42,
       43,   44,   45,   46,   48,   48,   51,   51,   57,   52,
       52,   61,   92,   67,  120,   49,   49,   63,   76,   77,
       79,   80,   96,  117,  116,  113,   62,   97,   58,   68,
       64,   65,   96,  111,   93,  110,  108,  123,   53,   53,
       69,   69,   69,   69,   69,   69,   69,   81,   81,   81,

       81,   81,   81,   81,   81,   86,   87,   88,   89,   90,
       81,  107,  106,  105,  123,   82,   70,   71,   72,   73,
       74,  104,   82,   99,   99,   99,  103,  100,   99,   99,
       99,  102,  100,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,   47,   47,   47,   47,   47,   47,
       47,   50,   50,   50,   50,   50,   50,   50,   59,   59,
       59,  101,   59,   59,   59,   81,   81,   81,   83,   83,
       83,   85,   85,   95,   95,   95,   95,   95,   95,   95,
       98,   98,   94,   98,   98,   98,   98,  109,   91,  109,

      112,  112,  112,  114,  114,  114,  115,  115,  115,  118,
      118,  118,  119,  119,  119,  121,   84,  121,  121,  121,
      121,  121,   78,   75,  123,   66,   60,   56,   55,   54,
      123,    7,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123
    } ;

static yyconst short int yy_chk[287] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,   17,    5,
        6,   22,   44,   26,  117,    3,    4,   24,   31,   31,
       33,   33,   49,  102,   85,   83,   22,   49,   17,   26,
       24,   24,   96,   80,   44,   76,   73,   96,    5,    6,
       27,   27,   27,   27,   27,   27,   27,   40,   40,   40,

       40,   40,   40,   40,   42,   42,   42,   42,   42,   42,
       42,   72,   71,   70,   69,   40,   27,   27,   27,   27,
       27,   66,   42,   52,   52,   52,   59,   52,   99,   99,
       99,   55,   99,  120,  120,  120,  120,  120,  120,  120,
      121,  121,  121,  121,  121,  121,  121,  122,  122,  122,
      122,  122,  122,  122,  124,  124,  124,  124,  124,  124,
      124,  125,  125,  125,  125,  125,  125,  125,  126,  126,
      126,   53,  126,  126,  126,  127,  127,  127,  128,  128,
      128,  129,  129,  130,  130,  130,  130,  130,  130,  130,
      131,  131,   46,  131,  131,  131,  131,  132,   43,  132,

      133,  133,  133,  134,  134,  134,  135,  135,  135,  136,
      136,  136,  137,  137,  137,  138,   41,  138,  138,  138,
      138,  138,   32,   29,   28,   25,   21,   16,   14,   12,
        7,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lang\\Tokens.Lex"
#define INITIAL 0
#define com 1

#define string 2

#line 4 ".\\lang\\Tokens.Lex"
/* TOKENS.LEX -- Copyright (c) 1999-2003 Julian Mensch
     Contains the lexical analyzer for the IncursionScript resource
	 compiler. Designed to be fed into FLex (a GNU Lex clone) to produce
	 tokens.cpp.
*/

#include "Incursion.h"
#include "yygram.h"
#ifdef WIN32
#include <io.h>
#endif
#include <string.h>
#include <setjmp.h>
#include <ctype.h>
#define YY_NEVER_INTERACTIVE 1
extern int16 Errors;
extern void yywarning(const char*);
char yyMap[60000];
char preprocFilename[1024]; 

uint16 yyMapSize[512];

int LitCount=0,MapCount=0;
int16 test_val = 0, brace_level = 0, decl_state = 0, if_cond = 0,
                    paren_level = 0;
void  CatLiteral(const char*);
Dice & ParseDice(const char *c_str);

int32 lpos;
#ifdef DEBUG
char LBuff[257000];
#else
char LBuff[1];
#endif
hText ht;

extern String textSeg;
extern String dataSeg;
extern SymbolTable theSymTab;

/* Really, this could go in TABLES.CPP, but it's just simpler for
   many reasons to put it here -- it doesn't really need to be a
   global for one thing. Keywords1 lists the keywords that are
   recognized as such anywhere they appear in an .IRC file, while
   Keywords2 lists keywords that are treated as such only outside
   of code blocks, and can thus be used as variable names in code
   sections. This is important, for example, because "xval" is
   both a keyword used in effect stat blocks, as well as a member
   variable of the T_EVENTINFO object. Note also that keywords are
   case sensitive inside code blocks, but case insensitive else-
   where. Identifiers are always case sensitive. This sounds
   strange, but works well in practice. */

TextVal Keywords1[] = {
  { ABS, "abs" },           { CONTINUE, "continue" },
  { BREAK, "break" },       { CASE, "case" },         { DEFAULT, "default" },
  { DO, "do" },             { ELSE, "else" },         { WORD_FALSE, "false" },
  { FOR, "for" },           { HOBJ, "hObj" },         { HTEXT, "hText" },
  { INT16, "int16" },       { INT32, "int32" },       { IF, "if" },             
  { INT8, "int8" },         { WORD_MAX, "max" },      { MEMBER, "member" },
  { WORD_MIN, "min" },      { RETURN, "return" },     { RID, "rID",  },
  { STATIC, "static" },     { STRING, "string" },     { STRING, "String" },
  { SWITCH, "switch" },     { WORD_TRUE, "true" },    { WORD_NULL, "NULL" },
  { VOID, "void",  },       { WHILE, "while" },       { WORD_RECT, "rect" },
  { WORD_RECT, "Rect" },    { 0, NULL } };

  
TextVal Keywords2[] = {
  { ABILITY, "Ability" },   { ACC, "Acc" },           { ALIGN, "Align"},
  { ALL, "All" },           { ALSO, "Also" },         { AND, "And" },
  { WORD_ANY, "Any" },
  { APTITUDES, "Aptitudes"},{ ARCHERY, "Archery" },   { ARM, "Arm",  },
  { ARTIFACT, "Artifact" }, { AS, "As" },             { AT,  "At" },
  { ATTACK, "Attk" },       { AVAL, "aval",  },       { BASE, "Base" },
  { BLESSED, "Blessed" },   { BRAWL, "Brawl" },       { BRIGHT, "Bright" },
  { CHANCE, "Chance" },     { CLASS, "class",  },     { CASTER, "caster" },
  { WORD_COLOR, "Colour" },  { CONSTANTS, "Constants" }, { CAPACITY, "capacity" },
  { COST, "Cost" },         { DMG, "damage",  },      { COVERAGE, "Coverage" },
  { COVERAGE, "Cov" },      { CTYPE, "CType" },       { WORD_FILE, "File" },
  { WORD_CR, "CR" },        { CRIT, "Crit" },         { CURSED, "Cursed" },
  { CVAL, "cval" },         { DMG, "Dam" },           { DARK, "Dark" },
  { DAY, "Day" },           { WORD_DC, "DC" },        { DEF, "Def" },
  { WORD_DESC, "desc" },    { DEPTH, "Depth" },       { DISEASE, "Disease" },
  { DOOR, "door" },         { DMG, "Dmg" },           { FAVORED, "Favoured" },
  { FAVORED, "Favoured" },  { FLAVOR, "Flavour" },
  { DOMAINS, "domains" },   { DOMAIN, "domain" },     { DUNGEON, "Dungeon" },
  { DVAL, "dval" },         { EFFECT, "Effect" },     { EXPORT, "Export" },
  { WORD_ENCOUNTER, "Encounter"},{ BEHAVIOUR, "Behaviour" }, { PARTS, "Parts" },
  { EQUIP, "Equip" },       { EVAL, "eval" },         { EVENT, "Event" },
  { EVERY, "Every" },       { FACTOR, "Factor" },     { FEATS, "Feats" },
  { FEAT, "Feat" },         { FEATURE, "Feature" },   { FIRES, "Fires" },
  { FLAGS, "Flags" },       { FLOOR, "Floor" },       { FROM, "From" },
  { GEAR, "Gear" },         { GLYPH, "Glyph" },       { GOD, "God" },
  { GRANTS, "Grants" },     { GRID, "Grid" },         { GROUP, "Group" },
  { GUILD, "Guild" },       { HEAVY, "Heavy" },       { HIT, "Hit" },
  { HITDICE, "HitDice" },   { HITPOINTS, "Hitpoints"},{ HITDICE, "HD",  },
  { HITPOINTS, "HP" },      { IMAGE, "Image" },       { IMMUNE, "Immune" },
  { IMMUNE, "Imm" },        { INNATE, "Innate" },     { INVOKE, "Invoke" },
  { ITEM, "Item" },         { LDMG, "LDam" },         { LDMG, "LDmg" },
  { WORD_LEVEL, "Lev" },    { WORD_LEVEL, "Level" },  { WORD_LEVEL, "Levels" },
  { LIFESPAN, "Lifespan" }, { FUEL, "Fuel" },
  { LIGHT, "Light" },       { LISTS, "Lists" },       { LVAL, "lval" },
  { MODULE, "Module" },     { MANA, "Mana" },         { MAP, "Map" },
  { MATERIAL, "Mat" },      { MATERIAL, "Material" }, { MELEE, "Melee" },
  { MAX_SIZE, "MaxSize" },  { MTYPE, "MType" },       
  { MONSTER, "Monster" },   { MOVE, "Mov" },          { MOVE, "Move" },
  { NEAR, "Near" },         { NONE, "None" },         { NORMAL, "Normal" },
  { NPC, "NPC" },           { NUTRITION,"Nutrition" },{ NUTRITION, "Nut" },
  { OBJECTS, "Objects" },   { OBJECT, "Object" },     { OF, "Of" },
  { ON, "On" },             { OR, "Or" },             { OPTION, "Option" },
  { PARAMS, "Params" },     { PARRY, "Parry" },       { PARTS, "Parts" },
  { PARTIAL, "Partial" },   { PENALTY, "Penalty" },   { PURPOSE, "purpose" },
  { PER, "Per" },           { POWER, "power" },       { POISON, "poison" },
  { PVAL, "pval" },         { PROFICIENCIES, "Proficiencies" },
  { PROFICIENCIES, "Prof"}, { PROP, "prop" },         { PROP, "property" },
  { QUALITIES, "Qualities"},{ QUEST, "Quest" },       { QVAL, "qval"  },
  { RACE, "race" },         { RANDOM, "random" },     { RATING, "rating" },
  { REGIONS, "regions" },   { REGION, "region" },     { RANGE, "range" },
  { RESISTS, "res" },       { RESISTS, "Resists" },   { SLOT, "slot" },
  { ROOMTYPES, "roomtypes"},{ ROUTINE, "routine" },   { RVAL, "rval" },
  { SAVES, "save" },        { SAVES, "Sav" },         { SAVES, "Saves" },
  { SDMG, "SDam" },         { SDMG, "SDmg" },         { SIZE, "Size" },
  { SIZE, "Siz" },          { SKILLS, "Skills" },     { SPECIALS, "Specials" },
  { SPEED, "Spd" },         { SPEED, "Speed" },       { SPELL, "Spell" },
  { SPELLS, "Spells" },     { START, "Start" },       { STARTING, "Starting" },
  { STATI, "Stati" },       { STOCK, "Stock" },       { STORE, "Store" },
  { SUSTAINS, "Sustains" }, { SVAL, "sval" },         { SYSTEM, "system" },
  { WORD_TARGET, "target" },{ WEIGHT_LIM, "WeightLim" },{ WEIGHT_MOD, "WeightMod" },
  { WORD_TEMPLATE, "Template" }, { TERRAIN, "Terrain" },   { TEXT, "Text" },
  { THREAT, "Threat" },     { THROWING, "Throwing" }, { THROWING, "Thrown" },
  { TILE, "Tile" },         { TILES, "Tiles" },       { TIMEOUT, "Timeout" },
  { TO, "to" },
  { TURNS, "Turns" },       { TYPE, "Type" },         { TVAL, "tval" },
  { VALUE, "Value" },       { VAR, "Var" },           { WALLS, "Walls" },
  { WEEK, "Week" },         { WEIGHT, "Weight" },     { WITH, "with" },
  { XVAL, "xval" },         { YVAL, "yval" },         { 0, NULL } }; 

TextVal AttrWords[] = {
  { A_STR, "Str" },         { A_DEX, "Dex" },         { A_CON, "Con" },
  { A_INT, "Int" },         { A_WIS, "Wis" },         { A_CHA, "Cha" },
  { A_LUC, "Luc" },         { A_LOY, "Loy" },         { 0, NULL } };

TextVal DirWords[] = {
  { NORTH, "North" },       { SOUTH, "South" },       { EAST, "East" },
  { WEST, "West",  },         { NORTHEAST, "Northeast"},{ NORTHWEST, "Northwest" },
  { SOUTHEAST, "Southeast"},{SOUTHWEST, "Southwest"},{ UP, "Up" },
  { DOWN, "Down" },         { CENTER, "Center" },     { 0, NULL } };

TextVal ColourWords[] = {
  { BLACK, "black" },       { GREY, "grey" },         { GREY, "gray" },
  { WHITE, "white" },       { BLUE, "blue" },         { GREEN, "green" },
  { RED,   "red"   },       { PURPLE, "purple" },     { CYAN, "cyan" },
  { MAGENTA, "magenta" },   { YELLOW, "yellow" },     { AZURE, "azure" },
  { SKYBLUE, "sky" },       { PINK, "pink" },         { BROWN, "brown" },
  { SKYBLUE, "skyblue" },   { SHADOW, "shadow" },     { 0, NULL } };



YYSTYPE DoKeywords(const char *text)
  {
    int16 i;
    if (brace_level >= 2 || decl_state || if_cond) {
      for (i=0;Keywords1[i].Val;i++)
        if (strcmp(text,Keywords1[i].Text)==0)
          return Keywords1[i].Val;
      yylval = theSymTab.Add(text);
      return IDENT;
      }                        
    else {
      for (i=0;Keywords1[i].Val;i++)
        if (stricmp(text,Keywords1[i].Text)==0)
          {
            if (Keywords1[i].Val == INT16 || Keywords1[i].Val == INT8 ||
                Keywords1[i].Val == INT32 || Keywords1[i].Val == STRING ||
                Keywords1[i].Val == HTEXT || Keywords1[i].Val == HOBJ ||
                Keywords1[i].Val == RID || Keywords1[i].Val == WORD_RECT)
              decl_state = true;
            if (Keywords1[i].Val == IF && brace_level < 2)
              if_cond = 1;
            return Keywords1[i].Val;
          }
      
      for (i=0;Keywords2[i].Val;i++)
        if (stricmp(text,Keywords2[i].Text)==0)
          {
            if (Keywords2[i].Val == ROUTINE)
              decl_state = 1;
            if (Keywords2[i].Val == SYSTEM)
              decl_state = 1;
            return Keywords2[i].Val;
          }

      for (i=0;AttrWords[i].Text;i++)
        if (stricmp(text,AttrWords[i].Text)==0)
          { yylval = AttrWords[i].Val; return ATTRIBUTE; }

      for (i=0;ColourWords[i].Text;i++)
        if (stricmp(text,ColourWords[i].Text)==0)
          { yylval = ColourWords[i].Val; return COLOR; }
      
      for (i=0;DirWords[i].Text;i++)
        if (stricmp(text,DirWords[i].Text)==0)
          { yylval = DirWords[i].Val; return DIRECTION; }

      if (stricmp(text,"slash")==0 || stricmp(text,"slashing")==0)
        { yylval = SLASH; return WEP_TYPE; }
      if (stricmp(text,"pierce")==0 || stricmp(text,"piercing")==0)
        { yylval = PIERCE; return WEP_TYPE; }
      if (stricmp(text,"blunt")==0)
        { yylval = BLUNT; return WEP_TYPE; }

      if (stricmp(text,"fort")==0)
        { yylval = FORT; return STYPE; }
      if (stricmp(text,"ref")==0)
        { yylval = REF; return STYPE; }
      if (stricmp(text,"will")==0)
        { yylval = WILL; return STYPE; }


      yyerror(Format("Illegal word token: \"%s\"\n",text));
      return ARCHERY;
      }
  }

#line 699 ".\\SRC\\tokens.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 229 ".\\lang\\Tokens.Lex"


#line 853 ".\\SRC\\tokens.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 124 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 123 );
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 231 ".\\lang\\Tokens.Lex"
{ sscanf(yytext,"#line \"%s %d",preprocFilename,&yypos);
                      yypos --; /* we'll read the \n next */
                      for (int16 i=0;preprocFilename[i] && i != 1022;i++)
                        {
                          if (preprocFilename[i] == '/')
                            preprocFilename[i] = '\\';
                          if (preprocFilename[i] == '\"')
                            preprocFilename[i] = 0;
                        }
                    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 242 ".\\lang\\Tokens.Lex"
{ return 'd'; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 248 ".\\lang\\Tokens.Lex"
{ yylval = yytext[1]; return CHAR_CONST; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 250 ".\\lang\\Tokens.Lex"
{ 
                     for (int32 i=0;yytext[i];i++)
                       if (islower(yytext[i]))
                         return DoKeywords(yytext);
                     yyerror(Format("Undefined Constant: %s (assuming value 0)\n",yytext));
                     yylval = 0; return NUMBER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 257 ".\\lang\\Tokens.Lex"
{ for (int32 i=0;yytext[i];i++)
                       if (islower(yytext[i]))
                         return DoKeywords(yytext);
                     yyerror(Format("Undefined Constant: %s (assuming value 0)\n",yytext));
                     yylval = 0; return NUMBER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 265 ".\\lang\\Tokens.Lex"
{ char ch1, ch2; int16 MapPos = 0, sz = -1, szl = 0; long ln = yypos;
         bool warned = false; char *c, *g;
         while ((ch1 = yyinput()) != ':' && ch1!=EOF) {
           ReenterMapLoop:
           if (ch1 != '\n' && ch1 != '\t' && ch1 != '\r' && ch1 != ' ')
             { yyMap[MapPos++] = ch1; szl++; }
           if (ch1 == '\n')
             {
               yypos++; /* adjust line number! */
               ln++;
               if (sz == -1)
                 {
                   if (szl)
                     sz = szl;
                 }
               else if (szl && sz != szl && !warned)
                 {
                   warned = true;
                   yyerror(Format("Error: Mismatched grid line at line %d.",ln));
                 }
               szl = 0;
             }
                
           }
         if (ch1 == EOF)
           { yyerror(Format("Error: Unterminated Map Grid starting at line %d.",yypos));
             return ARCHERY; }
         if ((ch2 = yyinput()) == '}')
           {
             if (warned)
               yyMap[0] = 0;
             yyMap[MapPos] = 0;
             c = g = &yyMap[0];
             while (*g) {
               if (iswhite(*g))
                 g++;
               else
                 *c++ = *g++;
               }
             *c = 0;
             
             yyMapSize[MapCount++] = sz + ((strlen(yyMap)/sz)*256);
             if (strlen(yyMap) % sz)
               Error("Map grid alignment error in yylex!");
             yylval = textSeg.GetLength();
             textSeg += yyMap;
             textSeg += 1; /* ASCII char 1, our seperator */
             return MAPAREA;
           }
         yyMap[MapPos++] = ch1;
         ch1 = ch2;
         goto ReenterMapLoop;
       }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 319 ".\\lang\\Tokens.Lex"
{ if (brace_level >= 2 || decl_state)
           return DoKeywords("x1");
         yylval = 1; return NUMBER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 322 ".\\lang\\Tokens.Lex"
{ if (brace_level >= 2 || decl_state)
           return DoKeywords("x2");
         yylval = 2; return NUMBER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 325 ".\\lang\\Tokens.Lex"
{ if (brace_level >= 2 || decl_state)
           return DoKeywords("x3");
         yylval = 3; return NUMBER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 328 ".\\lang\\Tokens.Lex"
{ if (brace_level >= 2 || decl_state)
           return DoKeywords("x4");
         yylval = 4; return NUMBER; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 331 ".\\lang\\Tokens.Lex"
{ if (brace_level >= 2 || decl_state)
           return DoKeywords("x5");
         yylval = 5; return NUMBER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 335 ".\\lang\\Tokens.Lex"
{ return SCOPE_OPER; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 336 ".\\lang\\Tokens.Lex"
{ return INCREMENT_OP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 337 ".\\lang\\Tokens.Lex"
{ return DECREMENT_OP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 338 ".\\lang\\Tokens.Lex"
{ return RSHIFT_OP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 339 ".\\lang\\Tokens.Lex"
{ return LSHIFT_OP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 340 ".\\lang\\Tokens.Lex"
{ return GE_OP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 341 ".\\lang\\Tokens.Lex"
{ return LE_OP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 342 ".\\lang\\Tokens.Lex"
{ return EQ_OP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 343 ".\\lang\\Tokens.Lex"
{ return NE_OP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 344 ".\\lang\\Tokens.Lex"
{ return AND_OP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 345 ".\\lang\\Tokens.Lex"
{ return OR_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 346 ".\\lang\\Tokens.Lex"
{ return ASSIGN_MULT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 347 ".\\lang\\Tokens.Lex"
{ return ASSIGN_ADD; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 348 ".\\lang\\Tokens.Lex"
{ return ASSIGN_SUB; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 349 ".\\lang\\Tokens.Lex"
{ return ASSIGN_DIV; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 350 ".\\lang\\Tokens.Lex"
{ return ASSIGN_MOD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 351 ".\\lang\\Tokens.Lex"
{ return ASSIGN_AND; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 352 ".\\lang\\Tokens.Lex"
{ return ASSIGN_OR; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 353 ".\\lang\\Tokens.Lex"
{ return ASSIGN_NEG; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 354 ".\\lang\\Tokens.Lex"
{ return ASSIGN_LSHIFT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 355 ".\\lang\\Tokens.Lex"
{ return ASSIGN_RSHIFT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 356 ".\\lang\\Tokens.Lex"
{ return ELLIPSIS; } 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 357 ".\\lang\\Tokens.Lex"
{ return MEMBER_OP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 359 ".\\lang\\Tokens.Lex"
{ return ':'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 360 ".\\lang\\Tokens.Lex"
{ brace_level++; return '{'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 361 ".\\lang\\Tokens.Lex"
{ brace_level--; return '}'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 362 ".\\lang\\Tokens.Lex"
{ decl_state = false; return ';'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 363 ".\\lang\\Tokens.Lex"
{ return '+'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 364 ".\\lang\\Tokens.Lex"
{ return '-'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 365 ".\\lang\\Tokens.Lex"
{ return ','; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 366 ".\\lang\\Tokens.Lex"
{ return '%'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 367 ".\\lang\\Tokens.Lex"
{ return '/'; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 368 ".\\lang\\Tokens.Lex"
{ return '|'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 369 ".\\lang\\Tokens.Lex"
{ return '!'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 370 ".\\lang\\Tokens.Lex"
{ return '@'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 371 ".\\lang\\Tokens.Lex"
{ return '#'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 372 ".\\lang\\Tokens.Lex"
{ return '$'; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 373 ".\\lang\\Tokens.Lex"
{ return '^'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 374 ".\\lang\\Tokens.Lex"
{ return '&'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 375 ".\\lang\\Tokens.Lex"
{ return '*'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 376 ".\\lang\\Tokens.Lex"
{ paren_level++; return '('; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 377 ".\\lang\\Tokens.Lex"
{ paren_level--; 
         if (!paren_level) 
           if_cond = 0;
         return ')'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 381 ".\\lang\\Tokens.Lex"
{ return '['; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 382 ".\\lang\\Tokens.Lex"
{ return ']'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 383 ".\\lang\\Tokens.Lex"
{ return '.'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 384 ".\\lang\\Tokens.Lex"
{ return '<'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 385 ".\\lang\\Tokens.Lex"
{ return '>'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 386 ".\\lang\\Tokens.Lex"
{ return '~'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 387 ".\\lang\\Tokens.Lex"
{ return '?'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 388 ".\\lang\\Tokens.Lex"
{ return '='; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 390 ".\\lang\\Tokens.Lex"
{ if(sscanf(yytext,"%x",&yylval)!=1)
                       Fatal("Error reading hex value in lexer!");
                     return NUMBER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 394 ".\\lang\\Tokens.Lex"
{ BEGIN(com); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 395 ".\\lang\\Tokens.Lex"
{ yypos++; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 396 ".\\lang\\Tokens.Lex"
{ }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 397 ".\\lang\\Tokens.Lex"
{ }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 398 ".\\lang\\Tokens.Lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 400 ".\\lang\\Tokens.Lex"
{ BEGIN(string); lpos = 0; ht = textSeg.GetLength(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 401 ".\\lang\\Tokens.Lex"
{ yypos++; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 402 ".\\lang\\Tokens.Lex"
{ /* We use string concatenation legitamately in mon4.irh.
                              Elsewhere, it's probably a typo in a message list. */
                           /*if (!strstr(preprocFilename,"mon4"))
                             yywarning("String Concatenation Warning.");*/ }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 406 ".\\lang\\Tokens.Lex"
{ CatLiteral("\\\""); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 407 ".\\lang\\Tokens.Lex"
{ CatLiteral(yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 408 ".\\lang\\Tokens.Lex"
{ LBuff[lpos++] = 1;
                           LBuff[lpos] = 0;
                           textSeg += LBuff;
                           BEGIN(INITIAL); 
                           yylval = ht; 
                           return LITERAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 415 ".\\lang\\Tokens.Lex"
{ yylval = atoi(yytext); return NUMBER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 416 ".\\lang\\Tokens.Lex"
{ yylval = atoi(yytext); return NUMBER; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 417 ".\\lang\\Tokens.Lex"
{ yylval = atoi(yytext); return NUMBER; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 418 ".\\lang\\Tokens.Lex"
{ yylval = atoi(yytext); return NUMBER; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 419 ".\\lang\\Tokens.Lex"
{ yylval = atoi(yytext); return NUMBER; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 421 ".\\lang\\Tokens.Lex"
{ /* skip blank */ }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 422 ".\\lang\\Tokens.Lex"
{ /* skip blank */ }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 423 ".\\lang\\Tokens.Lex"
{ yypos++; /* adjust linenumber and skip newline */ }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 426 ".\\lang\\Tokens.Lex"
{ return DoKeywords(yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 427 ".\\lang\\Tokens.Lex"
{ return DoKeywords(yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 430 ".\\lang\\Tokens.Lex"
{ yyerror(Format("Illegal token '%s'\n", yytext));
         Errors++; if (Errors >= 4) yyterminate(); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 434 ".\\lang\\Tokens.Lex"
ECHO;
	YY_BREAK
#line 1451 ".\\SRC\\tokens.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(com):
case YY_STATE_EOF(string):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 124 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 124 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 123);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 434 ".\\lang\\Tokens.Lex"

  
void CatLiteral(const char*str)
  {
    int32 i;
    for(i=0;i<yyleng;i++)
      if (str[i] != '\"')
        {
          if (str[i] == '\\')
            switch(str[++i])
              {
                case 'n': LBuff[lpos++] = '\n'; break;
                case 't': LBuff[lpos++] = ' '; 
                          LBuff[lpos++] = ' '; break;
                case '\\': LBuff[lpos++] = '\\'; break;
                case '\"': LBuff[lpos++] = '\"'; break;
                case '<': LBuff[lpos++] = LITERAL_CHAR;
                          LBuff[lpos++] = '<'; break;
                case '>': LBuff[lpos++] = LITERAL_CHAR;
                          LBuff[lpos++] = '>'; break;
                case 0: break;
                default:
                  yyerror(Format("Unknown escape sequence at line %d.", yypos));
              }
          else {      
            if (i)
              if (isspace(str[i]) && isspace(str[i-1]))
                continue;
            /*if (str[i] == '_')
              { LBuff[lpos++] = ' '; }*/
            if(str[i] == '\r' || str[i] == '\n')
              { LBuff[lpos++] = ' '; yypos++; }
            else
              LBuff[lpos++] = str[i];
            }
          if (lpos >= 257000)
            Fatal("Single string literal longer than 256K characters!");

        }
    PurgeStrings();
  }

